### ISSUE TITLE
プロフィール

### ISSUE THREAD

**Issue by yamamoto-yuta** [yamamoto-yuta/GitHubIssuesCMS_sideM#1]
```yaml
# Site settins
blog_title: ENTER_TITLE_of_YOUR_BLOG
root_url: https://yamamoto-yuta.github.io/GitHubIssuesCMS_sideF
issues_edit_page: https://github.com/yamamoto-yuta/GitHubIssuesCMS_sideM/issues
favicon_url: https://user-images.githubusercontent.com/55144709/167446938-b7b243e2-0695-431e-8609-fffe0fbe1668.png
avatar_url: https://user-images.githubusercontent.com/55144709/167447026-a4b460a6-5afe-4291-9a01-bf13b7c90435.png

# Profile settings
author_name: ENTER_YOUR_NICK_NAME

author_description: ENTER_YOUR_SHORT_INTRODUCTION
copylight_name: ENTER_YOUR_NAME
copylight_url: https://github.com/yamamoto-yuta

# Ordered your SNS list
# Unnecessary items can be deleted (or commented out) and can be reordered.
sns:
  - name: GitHub
    url: https://github.com/yamamoto-yuta
```
